remote_theme: pages-themes/architect@v0.2.0
title: "ICRA 2024 Workshop - Wearable Intelligence for Healthcare Robotics: from Brain Minds to Body Movements"
color:
  gradient_left: "#FF3333"
  gradient_right: "#155799"
  header: "#fff"
  android_theme: "#000" # this default to gradient_color
  link: "#1e6bb8" # this default to gradient_color
  section_title: "#159957" # this default to gradient_color

syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

github: 
  is_project_page: false


